ai_news/urls.py
from django.urls import path

from .views import (
    index,
    ArticleListView,
    AddCommentView,
    ArticleDetailView,
    CreateArticleWithUrlView,
    CreateArticleManuallyForm,
    ArticleUpdateView,
    ArticleDeleteView,
    PublishersListView,
    PublisherCreateView,
    PublisherDetailView,
    TopicCreateView,
    like_view,
    confirm_logout
)

urlpatterns = [
    path("", index, name="index"),
    path("articles/", ArticleListView.as_view(), name="article-list"),
    path(
        "articles/create/",
        CreateArticleManuallyForm.as_view(),
        name="article-create-manually",
    ),
    path(
        "articles/create/url/",
        CreateArticleWithUrlView.as_view(),
        name="article-create-with-url",
    ),
    path(
        "articles/<int:pk>/comments/", AddCommentView.as_view(), name="comment-create"
    ),
    path("articles/<int:pk>/", ArticleDetailView.as_view(), name="article-detail"),
    path(
        "articles/<int:pk>/update/", ArticleUpdateView.as_view(), name="article-update"
    ),
    path(
        "articles/<int:pk>/delete/", ArticleDeleteView.as_view(), name="article-delete"
    ),
    path("publishers/", PublishersListView.as_view(), name="publisher-list"),
    path("publishers/create/", PublisherCreateView.as_view(), name="publisher-create"),
    path(
        "publishers/<int:pk>/", PublisherDetailView.as_view(), name="publisher-detail"
    ),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("likes/<int:pk>/", like_view, name="article_like"),
    path("confirm_logout/", confirm_logout, name="confirm-logout")
]

app_name = "ai_news"

news_site/urls.py
from django.contrib import admin
from django.urls import path, include

from ai_news.views import index


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ai_news.urls", namespace="ai_news")),
    path("accounts/", include("django.contrib.auth.urls")),
]

templates/includes/footer.html
  <footer class="footer pt-5 mt-5">
          <div class="text-center">
            <p class="my-4 text-sm">
              Soft UI Design System by &copy; <a target="_blank" href="https://bit.ly/3fKQZaL" target="_blank">Creative Tim</a> 
              - Coded by <a target="_blank" href="https://appseed.us" target="_blank">AppSeed</a>.
            </p>
          </div>
  </footer>

templates/includes/navigation-auth.html
  <div class="container position-sticky z-index-sticky top-0">
    <div class="row">
      <div class="col-12">
        <nav class="navbar navbar-expand-lg  blur blur-rounded top-0 z-index-fixed shadow position-absolute my-3 py-2 start-0 end-0 mx-4">
          <div class="container-fluid">
            <a class="navbar-brand font-weight-bolder ms-sm-3" 
               href="/" rel="tooltip" title="Designed and Coded by Creative Tim" data-placement="bottom">
              Soft UI Design System
            </a>
            <button class="navbar-toggler shadow-none ms-2" type="button" data-bs-toggle="collapse" data-bs-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon mt-2">
                <span class="navbar-toggler-bar bar1"></span>
                <span class="navbar-toggler-bar bar2"></span>
                <span class="navbar-toggler-bar bar3"></span>
              </span>
            </button>
            <div class="collapse navbar-collapse pt-3 pb-2 py-lg-0" id="navigation">
              <ul class="navbar-nav navbar-nav-hover ms-lg-12 ps-lg-5 w-100">
                <li class="nav-item ms-lg-auto">
                  <a class="nav-link nav-link-icon me-2" 
                     href="https://appseed.us/support/" target="_blank">
                    <i class="fa fa-rocket me-1"></i>
                    <p class="d-inline text-sm z-index-1 font-weight-bold" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Get Free Support">Support</p>
                  </a>
                </li>
                <li class="nav-item my-auto ms-3 ms-lg-0">
                  <a href="https://appseed.us/product/soft-ui-design-pro/django/" 
                     target="_blank" 
                     class="btn btn-sm  bg-gradient-primary btn-round mb-0 me-1 mt-2 mt-md-0">PRO Version</a>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <!-- End Navbar -->
      </div>
    </div>
  </div>

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">Prev</a></li>
    {% endif %}
  <li class="page-item active"><span class="page-link">{{ page_obj.number }}</span></li>
    {% if page_obj.has_next %}
      <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">Next</a></li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/scripts.html
  <script src="{{ ASSETS_ROOT }}/assets/js/core/popper.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/assets/js/core/bootstrap.min.js" type="text/javascript"></script>
  <script src="{{ ASSETS_ROOT }}/assets/js/plugins/perfect-scrollbar.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/assets/js/plugins/prism.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/assets/js/plugins/parallax.min.js"></script>

templates/includes/sidebar.html
<div class="container-fluid">
  <div class="row">
    <div class="col-2">
      <!-- Сайдбар -->
      <div class="btn-group-vertical btn-group-toggle" data-toggle="buttons">
        {% if user.is_authenticated %}
          <br>
          <p><strong>User: {{ user.get_username }}</strong></p>
          <form method="post" action="{% url 'ai_news:confirm-logout' %}">
            {% csrf_token %}
            <button type="submit" class="btn btn-secondary btn-block">Logout</button>
          </form>
        {% else %}
          <a href="{% url 'login' %}?next={{ request.path }}">
            <button type="button" class="btn btn-secondary btn-block">Login</button>
          </a>
        {% endif %}
        <a href="{% url 'ai_news:index' %}">
          <button type="button" class="btn btn-secondary btn-block">Home</button>
        </a>
        <a href="{% url 'ai_news:article-list' %}">
          <button type="button" class="btn btn-secondary btn-block">Articles</button>
        </a>
        <a href="{% url 'ai_news:publisher-list' %}">
          <button type="button" class="btn btn-secondary btn-block">Publishers</button>
        </a>
      </div>
      <!-- Кінець сайдбару -->
    </div>
    <div class="col-10">
      <!-- Основний контент -->
      {% block content %}{% endblock %}
      <!-- Кінець основного контенту -->
    </div>
  </div>
</div>