ai_news/urls.py
from django.urls import path

from .views import (
    index,
    ArticleListView,
    AddCommentView,
    ArticleDetailView,
    CreateArticleWithUrlView,
    CreateArticleManuallyForm,
    ArticleUpdateView,
    ArticleDeleteView,
    PublishersListView,
    PublisherCreateView,
    PublisherDetailView,
    TopicCreateView,
    like_view,
    confirm_logout
)

urlpatterns = [
    path("", index, name="index"),
    path("articles/", ArticleListView.as_view(), name="article-list"),
    path(
        "articles/create/",
        CreateArticleManuallyForm.as_view(),
        name="article-create-manually",
    ),
    path(
        "articles/create/url/",
        CreateArticleWithUrlView.as_view(),
        name="article-create-with-url",
    ),
    path(
        "articles/<int:pk>/comments/", AddCommentView.as_view(), name="comment-create"
    ),
    path("articles/<int:pk>/", ArticleDetailView.as_view(), name="article-detail"),
    path(
        "articles/<int:pk>/update/", ArticleUpdateView.as_view(), name="article-update"
    ),
    path(
        "articles/<int:pk>/delete/", ArticleDeleteView.as_view(), name="article-delete"
    ),
    path("publishers/", PublishersListView.as_view(), name="publisher-list"),
    path("publishers/create/", PublisherCreateView.as_view(), name="publisher-create"),
    path(
        "publishers/<int:pk>/", PublisherDetailView.as_view(), name="publisher-detail"
    ),
    path("topics/create/", TopicCreateView.as_view(), name="topic-create"),
    path("likes/<int:pk>/", like_view, name="article_like"),
    path("confirm_logout/", confirm_logout, name="confirm-logout")
]

app_name = "ai_news"

news_site/urls.py
from django.contrib import admin
from django.urls import path, include

from ai_news.views import index


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("ai_news.urls", namespace="ai_news")),
    path("accounts/", include("django.contrib.auth.urls")),
]

ai_news/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class Publisher(AbstractUser):
    date_of_registration = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.username


class Topic(models.Model):
    title = models.CharField(max_length=255)

    def __str__(self):
        return self.title


class Article(models.Model):
    CHOICES = (("from_url", "from_url"), ("from_user", "from_user"))
    title = models.CharField(max_length=500, null=True, blank=True)
    body = models.TextField(null=True, blank=True)
    pub_date = models.DateTimeField(auto_now_add=True)
    topic = models.ManyToManyField(Topic, blank=True, related_name="articles")
    publisher = models.ForeignKey(
        Publisher, on_delete=models.CASCADE, related_name="articles"
    )
    url = models.URLField(default="", blank=True, null=True)
    created_by = models.CharField(max_length=10, choices=CHOICES, default="from_user")
    likes = models.ManyToManyField(Publisher, blank=True, related_name="articles_liked")

    class Meta:
        ordering = ['-pub_date']

    def __str__(self):
        return self.title

    def total_likes(self):
        return self.likes.count()

    def split_into_paragraphs(self):
        return self.body.split('\n')


class Comment(models.Model):
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name="comments"
    )
    publisher = models.ForeignKey(
        Publisher, on_delete=models.SET_NULL, null=True, related_name="comments"
    )
    comment = models.TextField(blank=True, null=True)
    pub_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.publisher.username}: {self.article}"

ai_news/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.contrib.auth.forms import UserCreationForm

from .models import Article, Topic, Publisher, Comment
from .scrapper import AVAILABLE_SITES
from .scrapper import MitScrapper, WikipediaScrapper, WashingtonPostsScrapper


WIKIPEDIA_URL = "en.wikipedia.org"
WASHINGTON_POST_URL = "www.washingtonpost.com"
MIT_URL = "news.mit.edu"


class ArticleWithUrlForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.publisher_user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["topic"] = forms.ModelMultipleChoiceField(
            queryset=Topic.objects.all(), widget=forms.CheckboxSelectMultiple
        )

    class Meta:
        model = Article
        fields = [
            "topic",
            "url",
        ]

    def clean_url(self):
        url = self.cleaned_data["url"]
        if Article.objects.filter(url=url).exists():
            raise forms.ValidationError("This URL already exists.")

        if url.endswith("Main_Page"):
            raise ValidationError("You should choose an article")

        url_parts = url.split("/")
        if len(url_parts) < 3:
            raise ValidationError("Invalid URL format")

        url_part = url_parts[2]
        if url_part not in AVAILABLE_SITES:
            raise ValidationError("You should choose an available source")

        if len(url_part) < AVAILABLE_SITES[url_part]:
            raise ValidationError(f"You should choose an article from {url_part}")

        return url

    def clean(self):
        cleaned_data = super().clean()
        url = cleaned_data.get("url")
        if url:
            scrup = self.scrup(url)
            if not scrup.check_if_article():
                raise ValidationError("Invalid URL. Choose an article")

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.title, instance.body = self.parse_title_and_body_article(instance.url)
        instance.publisher = self.publisher_user
        if commit:
            instance.save()
            topics = self.cleaned_data["topic"]
            instance.topic.add(*topics)
        return instance

    def scrup(self, url):
        if WIKIPEDIA_URL in url:
            return WikipediaScrapper(url)
        elif WASHINGTON_POST_URL in url:
            return WashingtonPostsScrapper(url)
        elif MIT_URL in url:
            return MitScrapper(url)

    def parse_title_and_body_article(self, url):
        scrup = self.scrup(url)
        return scrup.parse_title(), scrup.parse_article()


class ArticleManuallyForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        self.publisher_user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["topic"] = forms.ModelMultipleChoiceField(
            queryset=Topic.objects.all(), widget=forms.CheckboxSelectMultiple
        )

    class Meta:
        model = Article
        fields = [
            "topic",
            "title",
            "body",
        ]

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.publisher_id = self.publisher_user.id
        if commit:
            instance.save()
            topics = self.cleaned_data["topic"]
            instance.topic.add(*topics)
        return instance


class CreateTopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = [
            "title",
        ]

    def clean_title(self):
        title = self.cleaned_data["title"]
        if Topic.objects.filter(title=title).exists():
            raise forms.ValidationError("This topic already exists.")
        return title


class PublisherCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Publisher
        fields = UserCreationForm.Meta.fields


class ArticleSearchForm(forms.Form):
    body = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Write here..."}),
    )


class CommentCreationForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            "comment",
        ]

    def __init__(self, *args, **kwargs):
        self.publisher = kwargs.pop("publisher", None)
        self.article = kwargs.pop("article", None)
        super(CommentCreationForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        instance = super(CommentCreationForm, self).save(commit=False)
        instance.publisher = self.publisher
        instance.article = self.article
        if commit:
            instance.save()
        return instance

ai_news/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy, reverse
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponseRedirect
from django.views import generic

from .forms import (
    ArticleWithUrlForm,
    ArticleManuallyForm,
    ArticleSearchForm,
    CreateTopicForm,
    CommentCreationForm,
    PublisherCreationForm,
)
from .models import Article, Publisher, Topic, Comment


def index(request):
    num_articles = Article.objects.count()
    num_publishers = Publisher.objects.count()
    num_topics = Topic.objects.count()
    all_topics = Topic.objects.all()
    context = {
        "num_articles": num_articles,
        "num_publisher": num_publishers,
        "num_topics": num_topics,
        "all_topics": all_topics,
    }

    return render(request, "ai_news/index.html", context=context)


class ArticleListView(generic.ListView):
    model = Article
    template_name = "ai_news/article_list.html"
    paginate_by = 12

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(ArticleListView, self).get_context_data(**kwargs)
        body = self.request.GET.get("body", "")
        context["search_form"] = ArticleSearchForm(initial={"body": body})
        return context

    def get_queryset(self):
        form = ArticleSearchForm(self.request.GET)
        if form.is_valid():
            return Article.objects.filter(body__icontains=form.cleaned_data["body"])
        return Article.objects.all()


class CreateArticleWithUrlView(LoginRequiredMixin, generic.CreateView):
    model = Article
    template_name = "ai_news/create_article_with_url.html"
    success_url = reverse_lazy("ai_news:article-list")
    form_class = ArticleWithUrlForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class CreateArticleManuallyForm(LoginRequiredMixin, generic.CreateView):
    model = Article
    form_class = ArticleManuallyForm
    success_url = reverse_lazy("ai_news:article-list")
    template_name = "ai_news/create_article_manually.html"

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class ArticleDetailView(generic.DetailView):
    model = Article

    def get_context_data(self, *args, **kwargs):
        context = super(ArticleDetailView, self).get_context_data()
        stuff = get_object_or_404(Article, pk=self.kwargs["pk"])
        total_likes = stuff.total_likes()
        context["total_likes"] = total_likes
        return context


class ArticleDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Article
    success_url = reverse_lazy("ai_news:article-list")


class ArticleUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Article
    success_url = reverse_lazy("ai_news:article-list")
    fields = ["title", "body"]
    template_name = "ai_news/create_article_manually.html"


class PublishersListView(generic.ListView):
    model = Publisher
    template_name = "ai_news/publisher_list.html"


class PublisherCreateView(generic.CreateView):
    form_class = PublisherCreationForm
    success_url = reverse_lazy("ai_news:index")
    template_name = "ai_news/publisher_form.html"

    def form_valid(self, form):
        user = form.save()
        login(self.request, user)
        return redirect("ai_news:index")


class PublisherDetailView(generic.DetailView):
    model = Publisher


class TopicCreateView(generic.CreateView):
    model = Topic
    form_class = CreateTopicForm
    success_url = reverse_lazy("ai_news:index")


@login_required
def like_view(request, pk):
    article = get_object_or_404(Article, id=pk)
    if article.likes.filter(id=request.user.id).exists():
        article.likes.remove(request.user)
    else:
        article.likes.add(request.user)
    return redirect(request.META.get("HTTP_REFERER"))


class AddCommentView(LoginRequiredMixin, generic.CreateView):
    model = Comment
    form_class = CommentCreationForm

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["publisher"] = self.request.user
        kwargs["article"] = self.get_article()
        return kwargs

    def form_valid(self, form):
        form.instance.publisher = self.request.user
        form.instance.article = self.get_article()
        return super().form_valid(form)

    def get_article(self):
        article_id = self.kwargs.get("pk")
        return get_object_or_404(Article, pk=article_id)

    def get_success_url(self):
        return reverse_lazy(
            "ai_news:article-detail", kwargs={"pk": self.kwargs.get("pk")}
        )


def confirm_logout(request):
    return render(request, 'ai_news/confirm_logout.html')

templates/ai_news/article_confirm_delete.html
{% extends 'layouts/base.html' %}

{% block content %}
  <h1>Delete Article?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <a href="{% url "ai_news:article-list" %}" class="btn btn-info">Cancel</a>
    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/ai_news/article_detail.html
{% extends 'layouts/base.html' %}

{% block content %}
  <h1>
    {{ article.title }}
  </h1>
  <p>
    {{article.pub_date}}
  </p>
  <div>
    {% for paragraph in article.split_into_paragraphs %}
  <p>{{ paragraph }}</p>
{% endfor %}
    {% if article.url %}
      <strong> Source: </strong><a href = {{article.url}}> {{article.url}}</a>
    {% endif %}
  </div>
  <br/><br/>
  <br/>
  <form action="{% url "ai_news:article_like" article.id %}"
        method="post">
    {% csrf_token %}
    <button type="submit" name="article_id" value="{{ article.id }}">
      {% if user in article.likes.all %}
      ❤️
      {% else %}
      🤍
      {% endif %}
    </button> {{ total_likes }}
  </form>
  <br>
  <h2><strong>Comments</strong></h2>
  {% if not article.comments.all %}
    <p>
      Not comments yet...
      <button type="button" class="btn btn-primary">
        <a href="{% url "ai_news:comment-create" article.id %}">Add first comment</a>
      </button>
    </p>
  {% else %}
    {% for comment in article.comments.all %}
      <div class="card">
        <div class="card-body">
          <h5 class="card-title">{{ comment.publisher.username }}</h5>
            <p class="card-text">{{ comment.comment }}</p>
            <p class="card-text">{{ comment.pub_date }}</p>
        </div>
      </div>
    {% endfor %}
    <br>
    <button type="button" class="btn btn-primary">
     <a href="{% url "ai_news:comment-create" article.id %}">Add comment</a>
    </button>
  {% endif %}
{% endblock %}

templates/ai_news/article_list.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
<form method="get" action="" class="form-inline">
  <div class="form-group flex-grow-1">
    {{ search_form.body }}
  <button type="submit" class="btn btn-primary">🔍</button>
    </div>
</form>
    <h1>Articles all
        <a href="{% url 'ai_news:article-create-manually' %}" class="btn btn-primary link-to-page">+</a>
    </h1>
<div class="container">
  {% for article in article_list %}
    {% if forloop.counter0|divisibleby:3 %}
      <div class="row">
    {% endif %}
    <div class="col-md-4">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ article.title }}</h5>
          <p class="card-text">{{ article.body|truncatechars_html:150 }}</p>
        </div>
        <div class="card-body">
          {% for topic in article.topic.all %}
            <strong>{{ topic.title }}</strong>
            <br>
          {% endfor %}
        </div>
        <div class="card-footer d-flex justify-content-between align-items-center">
          <small class="text-muted">
            <form action="{% url 'ai_news:article_like' article.id %}" method="post"> 
              {% csrf_token %}
              <button type="submit" name="article_id" value="{{ article.id }}">
                {% if user in article.likes.all %}
                  ❤️
                {% else %}
                  🤍
                {% endif %}
              </button> {{ article.total_likes }}
            </form>
          </small>
          <button type="button" class="btn btn-primary">
            <a href="{% url 'ai_news:article-detail' pk=article.id %}">Read more</a>
          </button>
        </div>
      </div>
    </div>
    {% if forloop.last or forloop.counter0|add:1|divisibleby:3 %}
      </div>
    {% endif %}
  {% endfor %}
      {% block pagination %}
        {% include "includes/pagination.html" %}
      {% endblock %}
</div>
  
{% endblock %}

templates/ai_news/comment_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
  <h1>Add Comment</h1>
  <form method="post">
    {% csrf_token %}
    {{ form| crispy }}
    <button type="submit">Save</button>
  </form>
{% endblock %}

templates/ai_news/confirm_logout.html
{% extends 'layouts/base.html' %}

{% block content %}
  <br><br>
  <h1>Are you sure?</h1>
  <br>
  <form action="{% url 'logout' %}" method="post">
    {% csrf_token %}
    <button type="button" class="btn btn-info">
      <a href="{% url "ai_news:index" %}">Cancel</a>
    </button>
    <input type="button" value="Yes" class="btn btn-danger">

    
  </form>
{% endblock %}

templates/ai_news/create_article_manually.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <br><br>
  <h1>{{ object|yesno:"Update,Create" }} Article</h1>
  <p> You can get it form verified website <br>   👇 <br>
      <button type="button" class="btn btn-primary">
        <a href="{% url 'ai_news:article-create-with-url' %}">Try it...</a>
      </button>
  </p>
  <p>Or you can add it manually</p>
  <form method="post">
    {% csrf_token %}
    {{ form|crispy }}
    {{ comment_formset.management_form }}

    {% for form in comment_formset.forms %}
        {{ form|crispy }}
    {% endfor %}
    <button type="submit">Save</button>
</form>
{% endblock %}

templates/ai_news/create_article_with_url.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Article</h1>
<form method="post">
    {% csrf_token %}
        <ul> You can add the article from the next sources:
        <li>
            <a href="https://en.wikipedia.org/">Wikipedia</a>
        </li>
        <li>
            <a href="https://www.washingtonpost.com/">The Washington Post</a> (This method takes 20-30 seconds)
        </li>
        <li>
            <a href="https://news.mit.edu/">MIT News</a>
        </li>
    </ul>
    <a href="{% url 'ai_news:article-create-manually' %}"><-</a>
    {{ form|crispy }}
    {{ comment_formset.management_form }}

    {% for form in comment_formset.forms %}
        {{ form|crispy }}
    {% endfor %}
    <button type="submit">Save</button>
</form>
{% endblock %}

templates/ai_news/index.html
{% extends 'layouts/base.html' %}

{% block title %} Presentation {% endblock title %}

<!-- Specific CSS goes HERE -->

{% block stylesheets %}{% endblock stylesheets %}

{% block body_class %} index-page {% endblock body_class %}

{% block content %}

  <header class="header-2">
    <div class="page-header section-height-75 relative" style="background-image:url('{{ ASSETS_ROOT }}/assets/img/curved-images/curved-11.jpg')">
      <div class="container">
        <div class="row">
          <div class="col-lg-7 text-center mx-auto">
            <h1 class="text-white pt-3 mt-n5">
              AI Insights: Exploring Innovation and Discovery
            </h1>
            <p class="lead text-white mt-3">
              <br />
            </p>
          </div>
        </div>
      </div>
      <div class="position-absolute w-100 z-index-1 bottom-0">
        <svg class="waves" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 24 150 40" preserveAspectRatio="none" shape-rendering="auto">
          <defs>
            <path id="gentle-wave" d="M-160 44c30 0 58-18 88-18s 58 18 88 18 58-18 88-18 58 18 88 18 v44h-352z" />
          </defs>
          <g class="moving-waves">
            <use xlink:href="#gentle-wave" x="48" y="-1" fill="rgba(255,255,255,0.40" />
            <use xlink:href="#gentle-wave" x="48" y="3" fill="rgba(255,255,255,0.35)" />
            <use xlink:href="#gentle-wave" x="48" y="5" fill="rgba(255,255,255,0.25)" />
            <use xlink:href="#gentle-wave" x="48" y="8" fill="rgba(255,255,255,0.20)" />
            <use xlink:href="#gentle-wave" x="48" y="13" fill="rgba(255,255,255,0.15)" />
            <use xlink:href="#gentle-wave" x="48" y="16" fill="rgba(255,255,255,0.95" />
          </g>
        </svg>
      </div>
    </div>
  </header>
  <section class="pt-3 pb-4" id="count-stats">
    <div class="container">
      <div class="row">
        <div class="col-lg-9 z-index-2 border-radius-xl mt-n10 mx-auto py-3 blur shadow-blur">
          <div class="row">
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"><span id="state1" countTo={{ num_articles }}>0</span>+</h1>
                <h5 class="mt-3">
                  <a href="{% url 'ai_news:article-list' %}">Articles</a>
                </h5>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4 position-relative">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary"> <span id="state2" countTo={{ num_publisher }}>0</span></h1>
                <h5 class="mt-3">
                  <a href="{% url 'ai_news:publisher-list' %}">Publishers</a>
                </h5>
              </div>
              <hr class="vertical dark">
            </div>
            <div class="col-md-4">
              <div class="p-3 text-center">
                <h1 class="text-gradient text-primary" id="state3" countTo={{ num_topics }}>0</h1>
                <h5 class="mt-3">Topics</h5>
              </div>
            </div>
          </div>
            <div class="container d-flex justify-content-center align-items-center">
              <div>
                <br><br>
                {% for topic in all_topics %}
                  <a href="{% url 'ai_news:article-list' %}">
                    <button type="button" class="btn btn-info">{{ topic.title }}</button>
                  </a>
                {% endfor %}
                  {% if request.user.is_authenticated %}
                    <a href="{% url 'ai_news:topic-create' %}" class="btn btn-primary link-to-page">Add Topic</a>
                {% endif %}
          </div>
      </div>
        </div>
      </div>
    </div>
  </section>

  
{% endblock content %}

<!-- Specific JS goes HERE --> 
{% block javascripts %}

  <script src="{{ ASSETS_ROOT }}/assets/js/plugins/countup.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/assets/js/plugins/choices.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/assets/js/plugins/rellax.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/assets/js/plugins/tilt.min.js"></script>
  <script src="{{ ASSETS_ROOT }}/assets/js/plugins/choices.min.js"></script>

  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDTTfWur0PDbZWPr7Pmq8K3jiDp0_xUziI"></script>
  <script src="{{ ASSETS_ROOT }}/assets/js/soft-design-system.min.js?v=1.0.1" type="text/javascript"></script>
  <script type="text/javascript">
    if (document.getElementById('state1')) {
      const countUp = new CountUp('state1', document.getElementById("state1").getAttribute("countTo"));
      if (!countUp.error) {
        countUp.start();
      } else {
        console.error(countUp.error);
      }
    }
    if (document.getElementById('state2')) {
      const countUp1 = new CountUp('state2', document.getElementById("state2").getAttribute("countTo"));
      if (!countUp1.error) {
        countUp1.start();
      } else {
        console.error(countUp1.error);
      }
    }
    if (document.getElementById('state3')) {
      const countUp2 = new CountUp('state3', document.getElementById("state3").getAttribute("countTo"));
      if (!countUp2.error) {
        countUp2.start();
      } else {
        console.error(countUp2.error);
      };
    }
  </script>

{% endblock javascripts %}

templates/ai_news/publisher_detail.html
{% extends 'layouts/base.html' %}

{% block content %}
  <h1>{{ publisher.pseudonym }}</h1>
  <p>Date of registration: {{ publisher.date_of_registration }}</p>

  {% if user.is_authenticated and publisher == user %}
    <p><strong>My articles:</strong></p>
        <table class="table">
          <thead class="thead-dark">
            <tr>
                
                  <th scope="col">Title</th>
                  <th scope="col">Update</th>
                  <th scope="col">Delete</th>
                
            </tr>
          </thead>
        <tbody>
        {% for article in publisher.articles.all %}
            <tbody>
    <tr>
      <td>
        <a href="{% url 'ai_news:article-detail' pk=article.pk %}">
          <strong>{{ article.title }}</strong>
        </a>
      </td>
      <td>
          <button type="button" class="btn btn-info">
            <a href="{% url 'ai_news:article-update' pk=article.pk %}">Update</a>
          </button>
      </td>
      <td>
        <button type="button" class="btn btn-danger">
          <a href="{% url 'ai_news:article-delete' pk=article.pk %}">Delete</a>
        </button>
      </td>
    </tr>

      {% empty %}
        <li>No articles found.
        <a href="{% url 'ai_news:article-create-manually' %}" class="btn btn-primary link-to-page">Just add...</a>
        </li>
      {% endfor %}
        </tbody>
    </table>

  {% else %}
    <p><strong>Articles by {{ publisher.username }}:</strong></p>
    <ul>
      {% for article in publisher.articles.all %}
        <li><strong><a href="{% url 'ai_news:article-detail' pk=article.pk %}">{{ article.title }}</a></strong></li>
      {% empty %}
        <li>No articles found.</li>
      {% endfor %}
    </ul>
  {% endif %}
{% endblock %}

templates/ai_news/publisher_form.html
{% extends 'layouts/base.html' %}

{% load crispy_forms_filters %}
{% block content %}
  <h1>Create publisher</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/ai_news/publisher_list.html
{% extends 'layouts/base.html' %}

{% block content %}
<h1>Our publishers</h1>
<table class="table">
  <thead>
    <tr>
      <th scope="col">Username</th>
      <th scope="col">Date of registration</th>
    </tr>
  </thead>
  <tbody>
    {% if publisher_list %}
      {% if request.user.is_authenticated %}
        <tr>
          <td>
            <a href="{% url 'ai_news:publisher-detail' pk=request.user.id %}">
              <strong>{{ request.user.username }}</strong>
            </a>
          </td>
          <td>
            {{ request.user.date_of_registration }}      
          </td>
        </tr>
      {% endif %}
      
      {% for publisher in publisher_list %}
        {% if request.user != publisher %}
          <tr>
            <td>
              <a href="{% url 'ai_news:publisher-detail' pk=publisher.id %}">
                {{ publisher.username }}
              </a>
            </td>
            <td>
              {{ publisher.date_of_registration }}
            </td>
          </tr>
        {% endif %}
      {% endfor %}
    {% endif %}
  </tbody>
</table>
{% endblock %}

templates/ai_news/topic_form.html
{% extends 'layouts/base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Create topic</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}